# メールテンプレートマスタ
TRUNCATE TABLE mail_template_master;
INSERT INTO mail_template_master (id,created_at,created_user_id,updated_at,updated_user_id,version,service_category,process_category,product_grp_master_id,mail_subject,mail_body,envelope_from) VALUES (37,'2019/7/9','COTOS','2019/7/9','COTOS',1,'1','1',10,'【電力】見積承認依頼メール{{replaceValue2}}様','{{replaceValue2}}様の見積の承認を依頼されました。' || CHR(10) || '商品グループ：{{replaceValue3}}' || CHR(10) || '見積番号：{{replaceValue6}}' || CHR(10) || 'コメント：{{replaceValue4}}' || CHR(10) || '下記リンクから確認してください。' || CHR(10) || '{{replaceValue5}}' || CHR(10) || '' || CHR(10) || '送信専用アドレスから送信しています。返信しないでください。',null);
INSERT INTO mail_template_master (id,created_at,created_user_id,updated_at,updated_user_id,version,service_category,process_category,product_grp_master_id,mail_subject,mail_body,envelope_from) VALUES (2001,'2019/09/17','COTOS','2019/09/17','COTOS',1,'102','0',10,'電力料金に関するご案内 {{replaceValue1}}','{{replaceValue1}}' || CHR(10) || 'ご担当者様' || CHR(10) || '' || CHR(10) || '日頃より弊社の電力供給サービスをご利用頂きありがとうございます。' || CHR(10) || '電力料金の請求に関するご案内です。' || CHR(10) || '' || CHR(10) || 'ご請求書と日別電力使用量を本メールに添付しております。' || CHR(10) || 'ご確認を宜しくお願いします。' || CHR(10) || '' || CHR(10) || 'なお、弊社からの「電力料金に関する案内」（本メール）は、原則として毎月第4営業日に発信しております。' || CHR(10) || '（土日祝日の場合は翌営業日）' || CHR(10) || '' || CHR(10) || '●請求書の開き方●' || CHR(10) || '①本メールに添付されている請求書をPCに保存してください。' || CHR(10) || '②保存した請求書をダブルクリックすると、パスワードを入力するウィンドウが開きます。' || CHR(10) || '③別に受信したパスワードメールに記載されているパスワードを入力し、OKを押下してください。' || CHR(10) || '　請求書のファイルが開きます。' || CHR(10) || '' || CHR(10) || '●その他のご案内●' || CHR(10) || '①電気需給約款[高圧]等は当社のウェブサイトに掲載しております。' || CHR(10) || '　　https://www.ricoh.co.jp/solution/electricity/high/' || CHR(10) || '' || CHR(10) || '②請求書ダウンロードサービス' || CHR(10) || '　　過去の請求関連帳票をWebよりダウンロード頂けます。' || CHR(10) || '　　　　https://www.myricoh.jp/' || CHR(10) || '　　※ご利用いただくためには、MyRICOHご利用登録が必要となります。' || CHR(10) || '　　※MyRICOHご利用登録後、約2～3営業日にて本サービスがご利用頂けます。' || CHR(10) || '' || CHR(10) || '【お問い合わせ窓口】' || CHR(10) || '電力コールセンター　0120-069-089　9:00～18:00（365日）' || CHR(10) || '' || CHR(10) || '【発行】' || CHR(10) || 'リコージャパン株式会社　電力業務担当' || CHR(10) || 
'ーーーーーーーーーー' || CHR(10) || '※本メールは、『電力料金に関するご案内』の送付先としてご登録いただいたお客様に配信しています。' || CHR(10) || '※ご担当が替わられている場合には、至急ご連絡くださいますようよろしくお願い申し上げます。' || CHR(10) || '※配信専用のメールアドレスよりお送りしております。' || CHR(10) || '　本メール返信によるお問い合わせにはお答えできませんのでご注意下さい。','zjc_oshiraseshindenryoku@ml.ricoh.com');
INSERT INTO mail_template_master (id,created_at,created_user_id,updated_at,updated_user_id,version,service_category,process_category,product_grp_master_id,mail_subject,mail_body,envelope_from) VALUES (2003,'2019/09/18','COTOS','2019/09/18','COTOS',1,'102','0',10,'[Password]電力料金に関するご案内 {{replaceValue1}}','別途お送りしている以下の対象メールに添付されている暗号ファイルのパスワードを通知いたします。' || CHR(10) || '以下の情報を参考に、本メールに記載されているパスワードをご使用ください。' || CHR(10) || '' || CHR(10) || '----------------------------------------' || CHR(10) || 'Password:' || CHR(10) || '{{replaceValue1}}' || CHR(10) || '----------------------------------------' || CHR(10) || '　パスワード入力は　コピー＆貼り付け　をご利用ください。' || CHR(10) || '' || CHR(10) || '対象メール:' || CHR(10) || 'Date: {{replaceValue2}}' || CHR(10) || 'From: {{replaceValue3}}' || CHR(10) || 'To: {{replaceValue4}}' || CHR(10) || 'Subject: 電力料金に関するご案内 {{replaceValue5}}' || CHR(10) || '' || CHR(10) || '' || CHR(10) || '※このメールのみ受信した場合' || CHR(10) || '添付ファイルが受信側メールサーバで拒否されている可能性がありますので、下記電力コールセンターまでお問合せください。' || CHR(10) || '' || CHR(10) || '' || CHR(10) || '【お問合わせ窓口】' || CHR(10) || '電力コールセンター　0120-069-089　9:00～18:00（365日）' || CHR(10) || '' || CHR(10) || '【発行】' || CHR(10) || 'リコージャパン株式会社　電力業務担当' || CHR(10) || '－－－－－－－－－－' || CHR(10) || '※配信専用のメールアドレスよりお送りしております。' || CHR(10) || '　本メール返信によるお問い合わせにはお答えできませんのでご注意下さい。' || CHR(10) || '','zjc_oshiraseshindenryoku@ml.ricoh.com');
INSERT INTO mail_template_master (id,created_at,created_user_id,updated_at,updated_user_id,version,service_category,process_category,product_grp_master_id,mail_subject,mail_body,envelope_from) VALUES (2005,'2019/09/18','COTOS','2019/09/18','COTOS',1,'102','0',10,'【リコージャパン電力】{{replaceValue1}}様　電気小売媒介手数料お支払通知','{{replaceValue1}}' || CHR(10) || 'ご担当者様' || CHR(10) || '' || CHR(10) || 'いつも大変お世話になっております。' || CHR(10) || 'リコージャパン株式会社　電力小売り担当です。' || CHR(10) || '' || CHR(10) || '早速ですが、{{replaceValue2}}にお振込予定の手数料の内容を送付致しますので' || CHR(10) || 'ご査収下さるようお願い申し上げます。' || CHR(10) || '' || CHR(10) || '' || CHR(10) || '【お問合わせ窓口】' || CHR(10) || '電力コールセンター　0120-069-089　9:00～18:00（365日）' || CHR(10) || '' || CHR(10) || '【発行】' || CHR(10) || 'リコージャパン株式会社　電力小売業務担当' || CHR(10) || '',null);

DROP SEQUENCE mail_template_master_seq;
CREATE SEQUENCE mail_template_master_seq;
ALTER SEQUENCE mail_template_master_seq INCREMENT BY 4 NOCACHE;
SELECT mail_template_master_seq.NEXTVAL FROM DUAL;
ALTER SEQUENCE mail_template_master_seq INCREMENT BY 1 CACHE 20;

